export const REDIS_KEYS = {
  ROOM: "ROOM:",
  ROOM_PLAYERS: "ROOM_PLAYERS:",
  PLAYER_ROOM: "PLAYER_ROOM:",
  PLAYER_SOCKET: "PLAYER_SOCKET:",
  ROUND: "ROUND:",
  STEP: "STEP:",
  TURN: "TURN:",
};
